//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatingUser
    {
        public int UserID { get; set; }
        public string UserEmail { get; set; }
        public string UserName { get; set; }
        public string UserPhone { get; set; }
        public string UserGender { get; set; }
        public string UserSex { get; set; }
        public Nullable<int> UserAge { get; set; }
        public Nullable<int> UserMaxDistance { get; set; }
        public string UserDistanceUnit { get; set; }
        public Nullable<bool> ShareMyFeed { get; set; }
        public Nullable<bool> ShowMeInTopPick { get; set; }
        public Nullable<bool> UserActvieStatus { get; set; }
        public Nullable<System.DateTime> UserLastSeen { get; set; }
        public string UserImage { get; set; }
        public Nullable<bool> RecommendSort { get; set; }
        public Nullable<double> LocationLatitude { get; set; }
        public Nullable<double> LocationLongititude { get; set; }
        public string LocationName { get; set; }
        public string UserInterest { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string AboutKarter { get; set; }
        public string LookingFor { get; set; }
        public string Profession { get; set; }
        public string Height { get; set; }
        public Nullable<bool> IsUserActive { get; set; }
        public Nullable<bool> IsSuperLikeSubscribed { get; set; }
        public string UserMartialStatus { get; set; }
        public string UserPassword { get; set; }
    }
}
