//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubscriptionPlan
    {
        public int PlanId { get; set; }
        public string UserEmail { get; set; }
        public string PlanDescription { get; set; }
        public Nullable<System.DateTime> PlanStartDate { get; set; }
        public Nullable<System.DateTime> PlanEndDate { get; set; }
        public Nullable<double> PlanAmount { get; set; }
        public Nullable<int> PlanMonths { get; set; }
        public Nullable<bool> IsPlanActive { get; set; }
    }
}
