//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMessage
    {
        public int MessageId { get; set; }
        public string MessageFrom { get; set; }
        public string MessageTo { get; set; }
        public string MessageType { get; set; }
        public Nullable<System.DateTime> MessageDateTime { get; set; }
        public string MessageContent { get; set; }
        public Nullable<bool> IsDeletedFrom { get; set; }
        public Nullable<bool> IsDeletedTo { get; set; }
        public Nullable<bool> IsSeen { get; set; }
    }
}
