//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatingApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPhoto
    {
        public int PhotoId { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UserEmail { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> PhotoLikes { get; set; }
    }
}
